#!/usr/bin/env bash
# NixOS Installer — LUKS + BTRFS + Disko + Flakes
# Run from NixOS live USB:
#   sudo nix --experimental-features "nix-command flakes" run github:YOUR_USER/nixos-config
#
# Or if you cloned the repo:
#   sudo ./install.sh
set -euo pipefail

# ─── Colors ────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'
info()  { echo -e "${CYAN}[INFO]${NC} $*"; }
ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
warn()  { echo -e "${RED}[WARN]${NC} $*"; }
header() { echo -e "\n${BOLD}══════════════════════════════════════════${NC}"; echo -e "${BOLD}  $*${NC}"; echo -e "${BOLD}══════════════════════════════════════════${NC}\n"; }

# ─── Preflight ─────────────────────────────────────────────────────────────
header "NixOS Installer"

if [[ $EUID -ne 0 ]]; then
  warn "This script must be run as root (or with sudo)."
  exit 1
fi

export NIX_CONFIG="experimental-features = nix-command flakes"

# ─── Locate flake source ──────────────────────────────────────────────────
if [[ -n "${FLAKE_DIR:-}" ]]; then
  FLAKE_SRC="$FLAKE_DIR"
elif [[ -f "$(dirname "${BASH_SOURCE[0]}")/flake.nix" ]]; then
  FLAKE_SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
else
  warn "Cannot locate flake.nix. Run from the repo directory or via 'nix run'."
  exit 1
fi

# ─── Gather parameters ────────────────────────────────────────────────────
header "Configuration"

echo "Available disks:"
lsblk -d -o NAME,SIZE,MODEL | grep -v "^loop"
echo ""
read -rp "Target disk [/dev/nvme0n1]: " DISK
DISK="${DISK:-/dev/nvme0n1}"

if [[ ! -b "$DISK" ]]; then
  warn "$DISK is not a valid block device!"
  exit 1
fi

read -rp "Hostname [nixbox]: " HOSTNAME
HOSTNAME="${HOSTNAME:-nixbox}"

read -rp "Username [tooster]: " USERNAME
USERNAME="${USERNAME:-tooster}"

echo ""
warn "ALL DATA ON $DISK WILL BE DESTROYED!"
read -rp "Type 'yes' to continue: " CONFIRM
if [[ "$CONFIRM" != "yes" ]]; then
  echo "Aborted."
  exit 1
fi

echo ""
info "Enter LUKS encryption passphrase:"
read -rs -p "Passphrase: " PASSPHRASE
echo ""
read -rs -p "Confirm passphrase: " PASSPHRASE2
echo ""

if [[ "$PASSPHRASE" != "$PASSPHRASE2" ]]; then
  warn "Passphrases do not match!"
  exit 1
fi

echo -n "$PASSPHRASE" > /tmp/luks-password
unset PASSPHRASE PASSPHRASE2

# ─── Prepare working directory ────────────────────────────────────────────
header "Preparing configuration"

WORKDIR="/tmp/nixos-install-workdir"
rm -rf "$WORKDIR"
cp -r "$FLAKE_SRC" "$WORKDIR"
chmod -R u+w "$WORKDIR"

# Generate settings.nix with user-provided values (disk only for now;
# luksUuid and resumeOffset are filled after disko runs)
cat > "$WORKDIR/settings.nix" << EOF
# Generated by install.sh at $(date -Iseconds)
{
  disk = "$DISK";
  hostname = "$HOSTNAME";
  username = "$USERNAME";
  luksUuid = "PLACEHOLDER";
  resumeOffset = "0";
}
EOF

ok "settings.nix written: disk=$DISK hostname=$HOSTNAME user=$USERNAME"

# ─── Run Disko ────────────────────────────────────────────────────────────
header "Partitioning and formatting (disko)"

# Similar to https://nixos.asia/en/nixos-install-disko
# Disko reads settings.nix directly (via import ./settings.nix in disko.nix)
nix run github:nix-community/disko -- --mode disko "$WORKDIR/disko.nix"

ok "Disk partitioned and mounted at /mnt"

# ─── Compute runtime values ──────────────────────────────────────────────
header "Computing boot parameters"

RESUME_OFFSET=$(btrfs inspect-internal map-swapfile -r /mnt/swap/swapfile)
info "resume_offset = $RESUME_OFFSET"

# Determine LUKS partition path
if [[ "$DISK" == *nvme* ]] || [[ "$DISK" == *mmcblk* ]]; then
  LUKS_PART="${DISK}p2"
else
  LUKS_PART="${DISK}2"
fi
LUKS_UUID=$(blkid -s UUID -o value "$LUKS_PART")
info "LUKS UUID = $LUKS_UUID"

# Rewrite settings.nix with final values
cat > "$WORKDIR/settings.nix" << EOF
# Generated by install.sh at $(date -Iseconds)
{
  disk = "$DISK";
  hostname = "$HOSTNAME";
  username = "$USERNAME";
  luksUuid = "$LUKS_UUID";
  resumeOffset = "$RESUME_OFFSET";
}
EOF

ok "settings.nix updated with runtime values"

# ─── Generate hardware-configuration.nix ──────────────────────────────────
header "Generating hardware-configuration.nix"

nixos-generate-config --root /mnt --dir "$WORKDIR"

# Remove auto-generated fileSystems and swapDevices — disko handles them
sed -i '/^\s*fileSystems\./,/^\s*};/d' "$WORKDIR/hardware-configuration.nix"
sed -i '/^\s*swapDevices/,/^\s*\];/d' "$WORKDIR/hardware-configuration.nix"

ok "hardware-configuration.nix generated (disko manages mounts)"

# ─── Install NixOS ────────────────────────────────────────────────────────
header "Installing NixOS"

mkdir -p /mnt/etc/nixos
cp "$WORKDIR"/*.nix /mnt/etc/nixos/
cp "$WORKDIR"/install.sh /mnt/etc/nixos/ 2>/dev/null || true
cp "$WORKDIR"/README.md /mnt/etc/nixos/ 2>/dev/null || true
cp "$WORKDIR"/.gitignore /mnt/etc/nixos/ 2>/dev/null || true

# Flakes require files to be tracked by git (staged is enough — no commit needed)
cd /mnt/etc/nixos
git init -q
git add -A

info "Running nixos-install (this may take a while)..."
nixos-install --flake "/mnt/etc/nixos#$HOSTNAME" --no-root-passwd

# ─── Verification ─────────────────────────────────────────────────────────
header "Verifying installation"

ERRORS=0

# Check bootloader installed
if [[ -d /mnt/boot/EFI/systemd ]] || [[ -d /mnt/boot/EFI/BOOT ]]; then
  ok "systemd-boot installed in /mnt/boot/EFI"
else
  warn "systemd-boot NOT found in /mnt/boot/EFI!"
  ERRORS=$((ERRORS + 1))
fi

# Check initrd exists
INITRD=$(find /mnt/boot -name "initrd*" -o -name "initramfs*" 2>/dev/null | head -1)
if [[ -n "$INITRD" ]]; then
  ok "initrd found: $INITRD"
else
  warn "No initrd found in /mnt/boot!"
  ERRORS=$((ERRORS + 1))
fi

# Check LUKS config is present in the built system
if nixos-enter --root /mnt -c "cat /etc/crypttab 2>/dev/null; bootctl status 2>/dev/null" | grep -q "nixos\|luks" 2>/dev/null; then
  ok "LUKS device 'nixos' referenced in boot config"
else
  # Also check via the generated initrd configuration
  if grep -r "nixos" /mnt/boot/loader/entries/ 2>/dev/null | grep -q "initrd"; then
    ok "Boot entries reference initrd"
  else
    info "Could not verify LUKS in boot entries (may still be fine with systemd initrd)"
  fi
fi

# Check resume parameter in kernel cmdline
if grep -r "resume_offset=$RESUME_OFFSET" /mnt/boot/loader/entries/ >/dev/null 2>&1; then
  ok "Hibernation resume_offset present in boot entries"
else
  # systemd-boot entries may embed this differently
  if nixos-enter --root /mnt -c "cat /proc/cmdline 2>/dev/null || true" | grep -q "resume_offset" 2>/dev/null; then
    ok "resume_offset configured"
  else
    info "resume_offset not verified in boot entries (check after first boot)"
  fi
fi

# Verify user exists in the built system
if nixos-enter --root /mnt -c "id $USERNAME" >/dev/null 2>&1; then
  ok "User '$USERNAME' exists in installed system"
else
  warn "User '$USERNAME' NOT found!"
  ERRORS=$((ERRORS + 1))
fi

# Quick systemd dry-run
info "Running activation dry-run..."
if nixos-enter --root /mnt -c "/nix/var/nix/profiles/system/bin/switch-to-configuration dry-activate" 2>&1 | tail -5; then
  ok "Dry activation completed"
else
  warn "Dry activation had issues (non-fatal)"
fi

if [[ $ERRORS -gt 0 ]]; then
  warn "$ERRORS verification check(s) failed. Review above."
  read -rp "Continue to password setup anyway? [y/N]: " CONT
  if [[ "$CONT" != "y" && "$CONT" != "Y" ]]; then
    echo "Aborting. System is installed but may have issues."
    exit 1
  fi
else
  ok "All checks passed!"
fi

# ─── Set user password ────────────────────────────────────────────────────
header "Set user password"

info "Set password for $USERNAME:"
nixos-enter --root /mnt -c "passwd $USERNAME"

# ─── Cleanup ──────────────────────────────────────────────────────────────
rm -f /tmp/luks-password

# ─── Done ─────────────────────────────────────────────────────────────────
header "Installation complete!"

echo -e "
${GREEN}Next steps:${NC}
  1. Reboot:  ${BOLD}reboot${NC}
  2. Remove USB stick
  3. Plymouth will show LUKS passphrase prompt
  4. Log in as ${BOLD}$USERNAME${NC}
  5. Push your config:
       cd /etc/nixos
       git remote add origin <your-repo-url>
       git push -u origin main
"
