# Generated by install.sh — contains hardware-specific values.
# Commit this file after installation. Regenerate if moving to new hardware.
{
  disk = "/dev/nvme0n1";
  hostname = "nixbox";
  username = "tooster";
  luksUuid = "PLACEHOLDER";
  resumeOffset = "0";
}
